---
title: "Workout01-vanessa-lyu"
author: "Vanessa"
date: "2019/3/2"
output: md_document
---

 

 
library(dplyr)
curry <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/stephen-curry.csv")
andre <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/andre-iguodala.csv")
green <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/draymond-green.csv")
durant <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/kevin-durant.csv")
thompson <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/klay-thompson.csv")
mutate(curry,name="Stephen Curry")
curry <- mutate(curry,name="Stephen Curry")
andre <- mutate(andre, name = "Adre Iguodala")
green <- mutate(green, name="Graymond Green")
durant <- mutate(durant, name="Kevin Durant")
thompson <- mutate(thompson,name="Klay Thompson")

curry <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/stephen-curry.csv")
andre <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/andre-iguodala.csv")
green <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/draymond-green.csv")
durant <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/kevin-durant.csv")
thompson <- read.csv("https://raw.githubusercontent.com/ucb-stat133/stat133-hws/master/data/klay-thompson.csv")

library(dplyr)
curry <- mutate(curry,name="Stephen Curry")
andre <- mutate(andre, name = "Adre Iguodala")
green <- mutate(green, name="Graymond Green")
durant <- mutate(durant, name="Kevin Durant")
thompson <- mutate(thompson,name="Klay Thompson")

levels(curry$shot_made_flag) <- c(levels(curry$shot_made_flag), "shot_no") 
curry$shot_made_flag[curry$shot_made_flag == "n"]  <- "shot_no" 
levels(green$shot_made_flag) <- c(levels(green$shot_made_flag), "shot_no") 
green$shot_made_flag[green$shot_made_flag == "n"]  <- "shot_no" 
levels(thompson$shot_made_flag) <- c(levels(thompson$shot_made_flag), "shot_no") 
thompson$shot_made_flag[thompson$shot_made_flag == "n"]  <- "shot_no" 
levels(andre$shot_made_flag) <- c(levels(andre$shot_made_flag), "shot_no") 
andre$shot_made_flag[andre$shot_made_flag == "n"]  <- "shot_no" 
levels(durant$shot_made_flag) <- c(levels(durant$shot_made_flag), "shot_no") 
durant$shot_made_flag[durant$shot_made_flag == "n"]  <- "shot_no" 

levels(curry$shot_made_flag) <- c(levels(curry$shot_made_flag), "shot_yes") 
curry$shot_made_flag[curry$shot_made_flag == "y"]  <- "shot_yes" 
levels(green$shot_made_flag) <- c(levels(green$shot_made_flag), "shot_yes") 
green$shot_made_flag[green$shot_made_flag == "y"]  <- "shot_yes" 
levels(thompson$shot_made_flag) <- c(levels(thompson$shot_made_flag), "shot_yes") 
thompson$shot_made_flag[thompson$shot_made_flag == "y"]  <- "shot_yes" 
levels(andre$shot_made_flag) <- c(levels(andre$shot_made_flag), "shot_yes") 
andre$shot_made_flag[andre$shot_made_flag == "y"]  <- "shot_yes" 
levels(durant$shot_made_flag) <- c(levels(durant$shot_made_flag), "shot_yes") 
durant$shot_made_flag[durant$shot_made_flag == "y"]  <- "shot_yes"


thompson <- mutate(thompson,minute=(period-1)*12+12-minutes_remaining)
curry <- mutate(curry,minute=(period-1)*12+12-minutes_remaining)
andre <- mutate(andre,minute=(period-1)*12+12-minutes_remaining)
green <- mutate(green,minute=(period-1)*12+12-minutes_remaining)
durant <- mutate(durant, minute=(period-1)*12+12-minutes_remaining)

write.csv(durant,"workout01/data/kevin-durant.csv")
write.csv(thompson,"workout01/data/klay-thompson.csv")
write.csv(green,"workout01/data/draymond-green.csv")
write.csv(andre,"workout01/data/andre-iguodala.csv")
write.csv(curry,"workout01/data/stephen-curry.csv")
 
durant_summary <- summary(durant)
durant_summary
sink("workout01/output/durant_summary.txt")
thompson_summary <- summary(thompson)
sink("workout01/output/thompson_summary.txt")
curry_summary <- summary(curry)
sink("workout01/output/curry_summary.txt")
andre_summary <- summary(andre)
sink("workout01/output/andre_summary.txt")
green_summary <- summary(green)
sink("workout01/output/green_summmary.txt")


shots_data <- rbind(curry, durant,green,andre,thompson)
shots_data
write.csv(shots_data,"workout01/data/shots-data.csv")
shots_data_summary <- summary(shots-data)
sink("workout01/output/shots-data_summary.txt")

library(dplyr)
library(ggplot2)
durant_scatterplot <- ggplot(data=durant)+geom_point(aes(x = x,y=y,color=shot_made_flag))
durant_scatterplot
court_file <- "workout01/images/nba-court.jpg"
install.packages("jpeg")
install.packages("grid")
library("jpeg")
library("grid")
court_image <-rasterGrob(readJPEG(court_file),width=unit(1,"npc"),height=unit(1,"npc"))
durant_shot_chart <-ggplot(data=durant)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart: Kevin Durant(2016 season)')+theme_minimal()
durant_shot_chart
curry_scatterplot <- ggplot(data=curry)+geom_point(aes(x = x,y=y,color=shot_made_flag))
curry_shot_chart <-
  ggplot(data=curry)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart: Stephen Curry (2016 season)')+theme_minimal() 
curry_shot_chart
andre_scatterplot <- ggplot(data=andre)+geom_point(aes(x = x,y=y,color=shot_made_flag))
andre_shot_chart <-
  ggplot(data=andre)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart: Andre Iguodala (2016 season)')+theme_minimal() 
andre_shot_chart
green_scatterplot <- ggplot(data=green)+geom_point(aes(x = x,y=y,color=shot_made_flag))
green_shot_chart <-
  ggplot(data=green)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart:Draymond Green (2016 season)')+theme_minimal()
green_shot_chart
thompson_scatterplot <- ggplot(data=green)+geom_point(aes(x = x,y=y,color=shot_made_flag))
thompson_shot_chart <-
  ggplot(data=thompson)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart: Klay Thompson (2016 season)')+theme_minimal() 
thompson_shot_chart
shots_chart_scatterplot <- ggplot(data=all_people)+geom_point(aes(x = x,y=y,color=shot_made_flag))
shots_chart <-
  ggplot(data=shots_data)+annotation_custom(court_image,-250,250,-50,420)+geom_point(aes(x=x,y=y,color=shot_made_flag))+ylim(-50,420)+ggtitle('Shot Chart:GSW(2016 season)')+theme_minimal() 
shots_chart
shots_chart+facet_grid(.~name)

library(readr)
library(dplyr)
 

two_PT <- filter(shots_data,shot_type == "2PT Field Goal")
two_PT2 <- summarise(group_by(two_PT,name),total=sum(shot_type == "2PT Field Goal"),made = sum(shot_made_flag=="y"),perc_made=made/total)
two_PT_effectie_shooting <- arrange(two_PT2,desc(perc_made))
two_PT_effectie_shooting
```

 
three_PT <- filter(shots_data,shot_type == "3PT Field Goal")
three_PT2 <- summarise(group_by(three_PT,name),total=sum(shot_type == "3PT Field Goal"),made = sum(shot_made_flag=="y"),perc_made=made/total)
three_PT_effectie_shooting <- arrange(three_PT2,desc(perc_made))
three_PT_effectie_shooting
```
 
effective_shooting <- summarise(group_by(shots_data,name),total=NROW(shot_type),made = sum(shot_made_flag=="y"),perc_made=made/total)
effective_shooting <- arrange(three_PT_effective_shooting,desc(perc_made))
effective_shooting
```
```{r}

```

